package main

import "os"
import "bufio"
import "strings"

// The code below was generated by ChatGPT

type Spec struct {
	Name		string
	Version		string
	Release		string
	Summary		string
	Description	string
	Packager	string
	PackagerEmail	string
	// Add more fields as needed based on your .spec file
}

func parseSpecFile(filePath string) (*Spec, error) {
	file, err := os.Open(filePath)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	spec := &Spec{}
	scanner := bufio.NewScanner(file)

	for scanner.Scan() {
		line := scanner.Text()
		parseSpecLine(line, spec)
	}

	if err := scanner.Err(); err != nil {
		return nil, err
	}

	return spec, nil
}

func parseSpecLine(line string, spec *Spec) {
	fields := strings.Fields(line)
	if len(fields) < 2 {
		return
	}

	switch fields[0] {
	case "Name:":
		spec.Name = fields[1]
	case "Version:":
		spec.Version = fields[1]
	case "Release:":
		spec.Release = fields[1]
	case "Packager:":
		spec.Packager = strings.Join(fields[1:len(fields)-1], " ")
		spec.PackagerEmail = fields[len(fields)-1]
		spec.PackagerEmail = strings.TrimLeft(spec.PackagerEmail, "<")
		spec.PackagerEmail = strings.TrimRight(spec.PackagerEmail, ">")
	case "Summary:":
		spec.Summary = strings.Join(fields[1:], " ")
	}
	// Add more cases based on your .spec file structure
}

